<h1>Novo Produto</h1>
<form method="POST">	
	<fieldset>		
		<legend>Informações do Produto</legend>

		<label for="descricao">Descrição</label>
		<input type="text" name="descricao" id="descricao" />	
	
		<label for="quantidade">Quantidade</label>
		<input type="text" name="quantidade" id="quantidade" />
	
		<label for="preco">Preço</label>
		<input type="text" name="preco" id="preco" />
	
		<input type="submit" name="Salvar Produto"; />
	</fieldset>
</form>